defaults: &defaults
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: 5
  host: localhost

development:
  <<: *defaults
  database: newepictube_dev
  username: newepictube
  password: 

test:
  <<: *defaults
  database: newepictube_test
  username: newepictube
  password: 
